<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/handlebars.js/1.0.rc.1/handlebars.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/1.9.0/jquery.js"></script>
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/jquery-ui.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery.blockUI/2.66.0-2013.10.09/jquery.blockUI.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/datatables/1.9.4/jquery.dataTables.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/scroller/1.1.0/js/dataTables.scroller.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery.form/3.46.0/jquery.form.js"></script>
<script type="text/javascript" src="https://unpkg.com/moment@2.4.0/moment.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/select2/3.4.2/select2.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/2.3.1/js/bootstrap.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.11.1/jquery.validate.js"></script>
<script type="text/javascript" src="lib/jquery.iframe-transport.js"></script>
<script type="text/javascript" src="lib/jquery.minicolors.min.js"></script>
<script type="text/javascript" src="lib/jquery.switchButton.js"></script>
<script type="text/javascript" src="lib/jquery.ui.timepicker.js"></script>
<script type="text/javascript" src="lib/jquery.ui.widget.js"></script>
<script type="text/javascript" src="lib/jquery.rating.pack.js"></script>
<script type="text/javascript" src="lib/jquery.MetaData.js"></script>
<script type="text/javascript" src="lib/jquery.rating.js"></script>