<link media="all" type="text/css" href="https://cdn.statically.io/gh/striderarun/files/main/bootstrap-responsive.css" rel="stylesheet">
<link media="all" type="text/css" href="https://cdn.statically.io/gh/striderarun/files/main/bootstrap.css" rel="stylesheet">
<link media="all" type="text/css" href="https://cdn.statically.io/gh/striderarun/files/main/filter-dropdown.css" rel="stylesheet">
<link media="all" type="text/css" href="https://cdn.statically.io/gh/striderarun/files/main/jquery-ui.css" rel="stylesheet">
<link media="all" type="text/css" href="https://cdn.statically.io/gh/striderarun/files/main/jquery.dataTables.css" rel="stylesheet">
<link media="all" type="text/css" href="https://cdn.statically.io/gh/striderarun/files/main/jquery.minicolors.css" rel="stylesheet">
<link media="all" type="text/css" href="https://cdn.statically.io/gh/striderarun/files/main/jquery.ratings.css" rel="stylesheet">
<link media="all" type="text/css" href="https://cdn.statically.io/gh/striderarun/files/main/jquery.switchButton.css" rel="stylesheet">
<link media="all" type="text/css" href="https://cdn.statically.io/gh/striderarun/files/main/jquery.ui.timepicker.css" rel="stylesheet">
<link media="all" type="text/css" href="https://cdn.statically.io/gh/striderarun/files/main/scroller.css" rel="stylesheet">
<link media="all" type="text/css" href="https://cdn.statically.io/gh/striderarun/files/main/select2.css" rel="stylesheet">