<link media="all" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/2.2.1/css/bootstrap-responsive.css" rel="stylesheet">
<link media="all" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/2.3.1/css/bootstrap.css" rel="stylesheet">
<link media="all" type="text/css" href="css/filter-dropdown.css" rel="stylesheet">
<link media="all" type="text/css" href="css/jquery-ui.css" rel="stylesheet">
<link media="all" type="text/css" href="css/jquery.dataTables.css" rel="stylesheet">
<link media="all" type="text/css" href="css/jquery.minicolors.css" rel="stylesheet">
<link media="all" type="text/css" href="css/jquery.switchButton.css" rel="stylesheet">
<link media="all" type="text/css" href="css/jquery.ui.timepicker.css" rel="stylesheet">
<link media="all" type="text/css" href="css/scroller.css" rel="stylesheet">
<link media="all" type="text/css" href="css/select2.css" rel="stylesheet">
<link media="all" type="text/css" href="css/jquery.rating.css" rel="stylesheet">